#!/bin/bash -e

# Script to download the latest rejected_patterns.yaml from openbmc-tools repository

URL="https://raw.githubusercontent.com/openbmc/openbmc-tools/master/tof-voters/config/rejected_patterns.yaml"
curl -s --output-dir "$(git rev-parse --show-toplevel)/config" -O "$URL"
