name: Prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Cache Prettier install
        uses: actions/cache@v4
        with:
          path: node_modules
          key: prettier-modules-${{ runner.os }}-3.6.2

      - name: Install Prettier
        run: npm install --save-dev prettier@3.6.2

      - name: Check formatting
        run: npx prettier --check "**/*.{css,html,json,yaml,yml}"
